name: x-Sync issue to Azure DevOps

on:
  workflow_call:

jobs:
  alert:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@v2.3
        env:
          ado_token: "${{ secrets.PA1_ADO_SYNC_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.PA1_ADO_SYNC_GH_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: "aznac"
          ado_project: "National DevSecOps"
          ado_wit: "User Story"
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Closed"
          ado_bypassrules: true
          log_level: 100